version: '3.9'

services:
  db:
    image: mysql:latest
    healthcheck:
      test: ["CMD", "ls"]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MajorProject
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    image: sukrutdekhane/spe_major_project_backend:latest
    environment:
      DB_URL: jdbc:mysql://db:3306/MajorProject?createDatabaseIfNotExist=true
      DB_USERNAME: myuser
      DB_PASSWORD: myuserpass
    networks:
      - backend-network
    ports:
      - "8081:8081"
    volumes:
      - backendlogs:backendlogs
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: sukrutdekhane/spe_major_project_frontend:latest
    networks:
      - backend-network
    ports:
      - "3000:3000"
    depends_on:
      - db

networks:
  backend-network:

volumes:
  db-data:
  backendlogs:
