---
- name: copy docker-compose file
  hosts: all
  tasks:
    - name: copy docker-compose file
      copy:
        src: ./docker-compose.yml
        dest: ./
    - name:  docker-compose down
      command: docker-compose down
    - name: run docker-compose file
      command: docker-compose up -d